### ISSUE TITLE
Clarity re: potatoes

### ISSUE THREAD

**Issue by dxf** [ianrenton/roastdinner#2]
First of all, this is bloody genius. Hats off!

Was just wondering whether there should be a step prior to "Once the potatoes have simmered for 10 minutes, drain them. Place some oil in the roasting dish, add the potatoes and add turn them to ensure they have a thin coating of oil on all sides. Return the dish to the oven."

That instructs user on how to prepare a roasting dish & insert in oven or am I being thick?

Merry Christmas!

**Comment by ianrenton** [comment]
Thanks, hope you had a good Christmas and a successful roast dinner!
I've made a quick change to add a line about pre-heating the oil for the potatoes, which I think is an improvement over putting them in cold oil, and hopefully provides more clarity to resolve this issue. Let me know what you think!

**Comment by dxf** [comment]
Fantastic.

Merry Christmas and have a great 2020!
