### ISSUE TITLE
Some way to add custom timings

### ISSUE THREAD

**Issue by jes** [ianrenton/roastdinner#4]
I don't have an exact UI in mind, but I think it would be useful to add a way to input additional timings.

(This isn't a feature request, so much as a request for comment. If you're on board and it seems sensible then I might look at adding it myself.)

For example, today I want to experiment with adding cauliflower cheese to the roast, so it would be great if I could click a little edit icon somewhere and input my own elements with my own timing, without having to first add it as a general-purpose food item in the source.

I don't know whether custom items would want to be entered with a fixed time-of-day or with a fixed time-before-dinner-is-served. I could see the argument either way. It probably doesn't make a lot of difference.

I wonder if the same idea could be used to edit the default timings. For example I prefer to heat the oil for the roast potatoes for 10 minutes rather than 5, and on my electric hobs it takes much longer for water to come to the boil than the timing chart seems to assume, so I just have to mentally account for the difference. It would be cool if I could edit the times so that the times on the chart are the times I have to use.

Btw I have probably made 10 or so roast dinners this year using this tool. It makes it so much easier and less stressful, I love it, thanks so much.

**Comment by ianrenton** [comment]
That sounds like a great feature! If you'd like to take a crack at it yourself, you're more than welcome. So long as the UI doesn't make things too complicated for the first-time casual user, I think it would be very useful to have the ability to add and customise timings on the fly. Depending on the implementation, custom ingredients/timing could even be saved as a cookie so it would remember next time you come back to the page.

**Comment by jes** [comment]
I've had a first pass in 048ec73. You can try it out here: https://jes.github.io/roastdinner/

It adds a "+" button next to each time in the chart. Clicking the "+" button pops up a prompt which asks for custom text. The custom text is then added to the chart just below the item that was clicked.

I think it's good enough for what I need, because it allows me to add custom text at any point throughout the timing. I didn't bother making it ask the user for a timestamp. It just associates each piece of text they enter with the timestamp of the item they clicked the "+" button on. If you want, you can type your own timestamp in the text.

One silly bug is that if you associate the custom text with a timestamp that later disappears (e.g. you change the weight of the meat, or you remove one of the sides), then your custom text disappears as well.

Other than the silly bug (which I'll fix unless this whole idea is a non-starter) - what do you think of this approach?

**Comment by ianrenton** [comment]
Looks good to me!

**Comment by jes** [comment]
Great, I've fixed the silly bug now, thanks!

**Comment by ianrenton** [comment]
Tested and working. I'd happily accept a pull request if you'd like this to be merged into the original version.

**Comment by jes** [comment]
Whoops, I thought I'd already done that! Sent pull request #6 

Thank you!

**Comment by ianrenton** [comment]
PR merged.
